business-api-ecosystem:
  # is the target environment openshift?
  openshift: true

  ## Marketplace OAuth and IdM configuration
  ##
  oauth:
    # URL of the FIWARE IDM used for user authentication
    server: https://login.ki-marktplatz.fiware.dev
    # OAuth2 Client ID of the BAE applicaiton
    clientId: marketplace-id
    # -- Callback URL path of frontend logic proxy for receiving the access tokens
    # (callback URL would be e.g. externalUrl/auth/aimarket/callback)
    callbackPath: /auth/aimarket/callback
    # -- IDP provider for passport strategy (fiware, keycloak, github, ...)
    provider: aimarket
    # -- Default role: Role to be used if no role is assigned to user (optional)
    defaultRole: seller
    

  ## External URL used to access the BAE frontend (logic proxy)
  ## Should match the host of the Ingress or Route of the Logic Proxy
  ##
  externalUrl: https://marketplace.ki-marktplatz.fiware.dev

  ## Configuration for biz-ecosystem-apis component
  ##
  bizEcosystemApis:
    ## Service account
    serviceAccount:
      create: false

    existingSecret: api-secret

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    ## -- deployment specific configuration
    deployment:
      ## -- configuration of the image to be used
      image:
        ## -- BAE APIs image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-apis
        repository: quay.io/fiware/biz-ecosystem-apis
        ## -- tag of the image to be used
        tag: v8.1.0-rc1
        ## -- specification of the image pull policy
        pullPolicy: IfNotPresent
      
    ## port that the APIs container uses
    port: 8080

    ## database configuration for APIs
    db:
      ## host of the database to be used
      host: mysql
      ## password for connecting the database
      password: dbPassword


      
  ## Configuration for biz-ecosystem-rss component
  ##
  bizEcosystemRss:
    ## Service account
    serviceAccount:
      create: false

    existingSecret: rss-secret

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    ## -- deployment specific configuration
    deployment:
      ## -- configuration of the image to be used
      image:
        ## -- BAE RSS image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-rss
        repository: quay.io/fiware/biz-ecosystem-rss
        ## -- tag of the image to be used
        tag: v8.0.0
        ## -- specification of the image pull policy
        pullPolicy: IfNotPresent
        #pullPolicy: Always
    
    ## port that the RSS container uses
    port: 8080
  
    ## database configuration for RSS
    db:
      ## host of the database to be used
      host: mysql
      ## URL connection string of the database to be used
      url: jdbc:mysql://mysql:3306/RSS



  ## Configuration for biz-ecosystem-charging-backend component
  ##
  bizEcosystemChargingBackend:
    ## Service account
    serviceAccount:
      create: false

    existingSecret: cb-secret
    
    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    ## -- deployment specific configuration
    deployment:
      ## -- configuration of the image to be used
      image:
        ## -- BAE Charging backend image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-charging-backend
        repository: quay.io/fiware/biz-ecosystem-charging-backend
        ## -- tag of the image to be used
        tag: v8.0.0
        ## -- specification of the image pull policy
        pullPolicy: IfNotPresent
          
    ## -- PVC configuration for charging backend plugins
    plugins:
      ## -- Enable the PVC for plugins storage
      enabled: true
      ## -- Annotations
      annotations:
        helm.sh/resource-policy: "keep"
      ## -- IDM Admin username
      idmUser: marketplace@ai-marketplace.fiware.io
    
    ## port that the charging backend container uses
    port: 8006

    ## payment configuration
    payment:
      ## method: paypal or None (testing mode payment disconected)
      method: paypal

    ## Paypal Oauth2 configuration
    paypal:
      ## Paypal Client-ID
      clientId: ATHrec61cupNwqrSFgARPY5FodDONQgy9P7yenZ7Tnfy34A-av4CpveHdYOJR_lp3GBxAyFZ0T-UuuM5

    ## database configuration for Charging backend (MongoDB)
    db:
      ## host of the database to be used
      host: mongodb
      ## Database name for connecting the database
      database: charging_db
      ## username for connecting the database
      user: charging

    ## -- Configuration for backing up the pvcs of the charging backend into a gcs-bucket
    backup:
      ## -- should the backup for file data be enabled
      enabled: false


  ## Configuration for biz-ecosystem-logic-proxy component
  ##
  bizEcosystemLogicProxy:
    ## Service account
    serviceAccount:
      create: false

    # references the already deployed secret.
    existingSecret: belp-secret

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    ## -- statefulset specific configuration
    statefulset:
      ## -- configuration of the image to be used
      image:
        ## -- BAE Logic Proxy image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-logic-proxy
        repository: quay.io/fiware/biz-ecosystem-logic-proxy
        ## -- tag of the image to be used
        #tag: v8.1.0-rc8
        tag: v8.1.0-dev
        ## -- specification of the image pull policy
        #pullPolicy: Always
        pullPolicy: IfNotPresent
    
    ## openshift specific route definition. Will not work on plain k8s
    route:
      ## -- should the deployment create openshift routes
      enabled: true
      # -- Routes that should be created
      routes:
        - tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
            # -- configuration for certificate generation.
            # -- see: https://github.com/FIWARE-Ops/fiware-gitops/blob/master/doc/ROUTES.md
          # -- host to be used
          #host: marketplace.ki-marktplatz.fiware.dev
          # -- tls configuration for the route
          certificate:
            issuer:
              kind: ClusterIssuer
              name: letsencrypt-aws-prod

    ## ingress configuration
    ## OpenShift: oc label namespace marketplace ingress=nginx
    ingress:
      ## should there be an ingress to connect keyrock with the public internet
      enabled: false
      

    ## port that the logic proxy container uses
    port: 8004

    ## Deployment in development or in production
    nodeEnvironment: production

    ## database configuration for Logic Proxy (MongoDB)
    db:
      # host of the database to be used
      host: mongodb
      # Database name for connecting the database
      database: belp_db
      # username for connecting the database
      user: belp

    ## -- elasticsearch configuration
    elastic:
      ## -- indexing engine of logic proxy
      engine: elasticsearch
      ## -- URL of elasticsearch service
      url: elasticsearch-master:9200
      ## -- API version of elasticsearch
      version: 7.5

    ## -- Base app path of logic proxy
    basePath: /opt/business-ecosystem-logic-proxy

    ## -- Custom theme configuration
    theme:
      ## -- Enable theme
      enabled: true
      ## -- Name of the theme
      name: KI-Marketplace
      ## -- Size of PVC to be created
      size: 4Gi
      ## Image which holds the theme files
      image: fiware/bae-ki-marketplace-theme:v0.0.7
      # -- specification of the image pull policy
      imagePullPolicy: Always
      ## Path to the source theme files inside the container
      #  Files will be copied to /themes/{{name}} with the PVC mounted at /themes
      sourcePath: /bae-ki-marketplace-theme

    # -- Allow users to edit party attributes
    allowEditParty: false


